### ISSUE TITLE
Missing AnimateTests.swift file

### ISSUE THREAD

**Issue by drhaynes** [JohnSundell/Animate#3]
Thanks for making this public. Really love it.

The `AnimateTests.swift` (and associated `AnimateTests.plist`) file is referenced in the Xcode project, but is missing in the repo. Which means that the testing scheme cannot be ran.

If they do indeed contain unit tests, it would be useful to have, especially when adding additional functionality.

**Comment by JohnSundell** [comment]
@drhaynes Happy to hear that you like it. At first I thought about making this a project that I'll maintain and keep adding to, but I don't think that'll happen (at least not at the moment, I simply don't have time for it 😅). Instead, I'd recommend to use it as a reference point (it's mostly an accessory to my 2-part blog posts: https://www.swiftbysundell.com/posts/building-a-declarative-animation-framework-in-swift-part-1) to build your own animation system using the techniques it presents.

I should update the README and Xcode project to reflect this, will do that at some point.

**Comment by drhaynes** [comment]
Sure thing, thanks for clarifying.
